spring:
  datasource:
    url: jdbc:mysql://52.200.8.101:3306/nyused
    username: root
    password: JgdzcxqJqrynPr9W9z91D2T2owG
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
